on:
  release:
    types: [prereleased]

name: Deploy to Stadion Dev

jobs:
  prerelease:
    name: Deploy to Stadion Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger update for the Dev service
        run: |
          echo ${GITHUB_REF##*/}
        
